### ISSUE TITLE
Sequelize update function

### ISSUE THREAD

**Issue by LCanix** [miage-lille/qsi-2-LCanix#1]
Bonjour,

J'ai une question (plus qu'un point de blocage) sur la fonction update.
Lorsque je l'utilise avec elephantSQL (qui si je ne me trompe pas est un base postgres) la fonction update me retourne un objet de type : 
`public static update(values: Object, options: Object): Promise<Array<affectedCount>>
`
Plus précisément [1]

Hors d'après la [doc ](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-update) elle devrait retourner un objet de type : 
`public static update(values: Object, options: Object): Promise<Array<affectedCount, affectedRows>>
`
D'après ce que j'ai pu voir [ici](https://stackoverflow.com/questions/38524938/sequelize-update-record-and-return-result) sur internet c'est dû au type de base de données. Pourtant le comportement d'une postgres n'est pas censé être le comportement que j'ai.

Avez-vous une explication ?

Ma solution pour esquiver le problème : 
```
export function updateUser(user) {
  return Users.update(user, { where: { id: user.id } }).then(modifiedUser => {
    logger.info('modifiedUser ${modifiedUser}');
    return Users.findById(user.id);
  });
```

**Comment by oteku** [comment]
Selon la doc, il faut passer l'option `returning:true`
Cela devrait marcher 
``` 
export function updateUser(user) {
  return Users.update(user, { where: { id: user.id } },{ returning : true } )
    .then(affectedCount, modifiedUser => {
      return Users.findById(modifiedUser.get({plain:true})); // attention à faire le omit dans le vrai code, je ne le met pas là pour lisibilité
  });
```

Sequelize permet d'adopter un style "Active Record" ou "Data Mapper" (que j'utilise) selon la préférence de l'utilisateur. 
Autre moyen de faire 

``` 
export function updateUser(user) {
  return Users.findById(user.id)
    .then(userToModify => {
      modifiedUser = { ...userToModify, ...user}; 
      modifiedUser.save();
      return modifiedUser.get({plain:true}); 
  });
```

**Comment by LCanix** [comment]
J'ai rapidement essayé les deux solutions ce midi, j'ai une erreur
Solution 1 : affectedCount n'est pas reconnu, problème de version Sequelize ? je suis en 4.31.2 ca me semble bon pourtant. Quoi qu'il en soit si je retire le affectedCount, j'ai une erreur sur modifiedUser.get qui n'existe pas.

Solution 2 : modifiedUser.get n'existe pas non plus.

D'après mes logs, l'objet retour est toujours 1, ce qui explique que .get n'existe pas.
Je creuse ce soir.
Merci de votre réponse :)

**Comment by oteku** [comment]
J'ai répondu devant mon café sans tester 👎  
... mais sinon lire correctement la doc ça aide ;)

Ce coup ci testé et les deux syntaxes fonctionnent 👍 
```
export function updateUser(user) {
  return Users.update(user, {
    where: { id: user.id },
    returning: true
  }).then(
    result => {
      const modifiedUser = result[1][0];
      return modifiedUser.get({ plain: true });
    }
  );
}
```

```
export function updateUser(user) {
  return Users.findById(user.id)
    .then(userToModify => {
      userToModify.firstName = user.firstName || userToModify.firstName;
      userToModify.lastName = user.lastName || userToModify.lastName;
      userToModify.email = user.email || userToModify.email;
      if (user.password) userToModify.hash = user.password;
      return userToModify.save();
    })
    .then(user =>
      _.omit(
        user.get({
          plain: true
        }),
        Users.excludeAttributes
      )
    );
}
```

Pour une api qui serait dans api/users 
```
apiUsersProtected.put('/', (req, res) =>
  updateUser({ ...req.body, id: req.user.id }).then(user =>
    res.status(201).send({
      success: true,
      profile: user,
      message: 'user modified'
    })
  )
);
```

**Comment by LCanix** [comment]
Ah !
En effet la doc dit que c'est un Array `Promise<Array<affectedCount, affectedRows>>` je me suis fait avoir aussi ! 
Merci pour la réponse 👍 
bonne semaine !
